language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'

env:
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.4.* SYMFONY_DEPRECATIONS_HELPER=weak

matrix:
  include:
    - php: 7.1
      env: SYMFONY_VERSION=4.2.* SYMFONY_DEPRECATIONS_HELPER=weak
    - php: 7.2
      env: SYMFONY_VERSION=4.2.* SYMFONY_DEPRECATIONS_HELPER=weak
    - php: 7.3
      env: SYMFONY_VERSION=4.2.* SYMFONY_DEPRECATIONS_HELPER=weak

before_script:
  - composer self-update
  - composer require symfony/framework-bundle:${SYMFONY_VERSION}

script: ./phpunit --coverage-clover build/logs/clover.xml
