language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'

env:
  - SYMFONY_VERSION=2.7.* SYMFONY_DEPRECATIONS_HELPER=weak
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.2.*
  - SYMFONY_VERSION=3.3.*

before_script:
  - composer self-update
  - composer require symfony/framework-bundle:${SYMFONY_VERSION}
  - composer require satooshi/php-coveralls

script: ./phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls
